const secretBank = [
 ['Momo','Chicken · Steam'],['Sel roti','Round · Oil'],['Dal bhat','Everyday · Plate'],['Chowmein','Noodles · Wok'],['Gundruk','Sour · Dry'],['Dhido','Hot · Spoon'],['Chatpate','Spicy · Street'],['Pani puri','Crispy · Water'],['Thukpa','Soup · Noodles'],['Sekuwa','Grill · Meat'],['Yomari','Sweet · Steam'],['Samosa','Triangle · Snack'],['Chiya','Milk · Cup'],['Aloo tama','Bamboo · Potato'],['Bara','Lentil · Fry'],['Choila','Spicy · Meat'],['Lassi','Cold · Yogurt'],['Juju dhau','King · Yogurt'],['Rasbari','Sweet · Syrup'],['Wai Wai','Crunchy · Packet'],
 ['Dashain','Tika · Swing'],['Tihar','Lights · Deusi'],['Bhai Tika','Brother · Money'],['Deusi Bhailo','Singing · Door'],['Teej','Red · Fasting'],['Holi','Colour · Water'],['Jatra','Mask · Crowd'],['Janti','Wedding · Dance'],['Dakshina','Elder · Money'],['Ping','Swing · Festival'],['Janai Purnima','Thread · River'],['Maghe Sankranti','Sesame · Winter'],['Lhosar','New · Year'],['Chhath','Sun · River'],
 ['Kathmandu','Traffic · Valley'],['Pokhara','Lake · Mountain'],['Thamel','Tourist · Street'],['Dharan','East · Hills'],['Ilam','Tea · Hills'],['Chitwan','Safari · Jungle'],['Lumbini','Buddha · Peace'],['Pashupatinath','Temple · Smoke'],['Swayambhunath','Monkey · Hill'],['Boudha','Stupa · Prayer'],['Nagarkot','Sunrise · View'],['Everest','Peak · Snow'],['Bhaktapur','Pottery · Square'],['Mustang','Wind · Desert'],['Rara Lake','Blue · Remote'],
 ['Aama ko phone','Calling · Worry'],['Mama ko chora','Comparison · Family'],['Kathmandu traffic','Horn · Jam'],['Chiya pasal','Talk · Cup'],['Lok Sewa','Exam · Dream'],['SEE','School · Results'],['Uni assignment','Deadline · Group'],['Driving test','Trial · Licence'],['Warehouse shift','Night · Work'],['PR tension','Visa · Future'],['Family pressure','Marriage · Questions'],['Bihe','Wedding · Family'],['Ghar farkine','Home · Flight'],['Bidesh jane','Airport · Dream'],['Load shedding','Dark · Candle'],['Microbus','Crowded · Fare'],['Tuk tuk','Three · Wheels'],
 ['PUBG','Squad · Chicken'],['Free Fire','Battle · Mobile'],['TikTok','Short · Dance'],['YouTube','Video · Subscribe'],['Facebook','Friends · Post'],['Pathao','Ride · Helmet'],['NTC','Network · SIM'],['WiFi','Password · Signal'],['Touch light','Battery · Dark'],['Ludo','Dice · Board'],['Carrom','Coins · Strike'],['eSewa','Digital · Pay'],['Khalti','Wallet · Scan'],['Mobile Legends','Team · Battle'],
 ['5 minute ma aauchhu','Late · Promise'],['Bholi garamla','Later · Delay'],['Paisaa chaina yaar','Broke · Friend'],['K gardai?','Chat · Question'],['Khana khayau?','Care · Dinner'],['Aba heram','Maybe · Later'],['La thik cha','Okay · Agree'],['K ho?','What · Surprise'],['Haina?','Right · Confirm'],['Kasto?','How · Curious'],['Ramailo','Fun · Vibe'],['Jhyau','Tired · Bored'],['Khattam','Finished · Bad']
];
// Every imposter clue is deliberately one indirect word: never a definition or a second clue.
const indirectHints = {
  'Momo':'Winter','Sel roti':'Grandma','Dal bhat':'Twice','Chowmein':'College','Gundruk':'Village','Dhido':'Ancestry','Chatpate':'Breaktime','Pani puri':'Trolley','Thukpa':'Cold','Sekuwa':'Smoke','Yomari':'Shape','Samosa':'Station','Chiya':'Morning','Aloo tama':'Sour','Bara':'Newar','Choila':'Feast','Lassi':'Summer','Juju dhau':'Royal','Rasbari':'Wedding','Wai Wai':'Hostel',
  'Dashain':'Money','Tihar':'Siblings','Bhai Tika':'Seven','Deusi Bhailo':'Doorstep','Teej':'Gathering','Holi':'Messy','Jatra':'Crowds','Janti':'Uncle','Dakshina':'Blessing','Ping':'Childhood','Janai Purnima':'Tradition','Maghe Sankranti':'January','Lhosar':'Community','Chhath':'Devotion',
  'Kathmandu':'Rush','Pokhara':'Weekend','Thamel':'Foreigners','Dharan':'East','Ilam':'Green','Chitwan':'Wild','Lumbini':'Quiet','Pashupatinath':'Farewell','Swayambhunath':'Mischief','Boudha':'Calm','Nagarkot':'Morning','Everest':'Expensive','Bhaktapur':'Ancient','Mustang':'Remote','Rara Lake':'Untouched',
  'Aama ko phone':'Worry','Mama ko chora':'Pressure','Kathmandu traffic':'Late','Chiya pasal':'Rumours','Lok Sewa':'Hope','SEE':'Nerves','Uni assignment':'Panic','Driving test':'Nerves','Warehouse shift':'Overtime','PR tension':'Waiting','Family pressure':'Questions','Bihe':'Relatives','Ghar farkine':'Nostalgia','Bidesh jane':'Goodbye','Load shedding':'Patience','Microbus':'Squeeze','Tuk tuk':'Shortcut',
  'PUBG':'Revive','Free Fire':'Survival','TikTok':'Attention','YouTube':'RabbitHole','Facebook':'Uncle','Pathao':'Urgent','NTC':'Coverage','WiFi':'Arguments','Touch light':'Emergency','Ludo':'Luck','Carrom':'Focus','eSewa':'Convenience','Khalti':'Balance','Mobile Legends':'Teamwork',
  '5 minute ma aauchhu':'Excuse','Bholi garamla':'Avoidance','Paisaa chaina yaar':'Awkward','K gardai?':'Boredom','Khana khayau?':'Affection','Aba heram':'Uncertainty','La thik cha':'Acceptance','K ho?':'Confusion','Haina?':'Doubt','Kasto?':'Judgement','Ramailo':'Company','Jhyau':'Mood','Khattam':'Disaster'
};
const els = Object.fromEntries(['setupScreen','handoffScreen','roleScreen','endScreen','countOutput','namesArea','imposterOptions','formError','currentPlayerName','roundNumber','progressFill','progressText','roleCard','roleIcon','roleTitle','roleLabel','roleValue','roleInstruction','nextBtn','musicBtn'].map(id=>[id,document.getElementById(id)]));
let count=4, imposterCount=1, game={players:[],round:0,recentSecrets:[],recentImposters:[],musicOn:false};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function optionsFor(n){return n<=5?[1]:n<=7?[1,2]:[1,2,3]}
function renderSetup(){els.countOutput.value=count;els.namesArea.innerHTML=Array.from({length:count},(_,i)=>`<input class="name-input" aria-label="Player ${i+1} name" placeholder="Player ${i+1} name" value="${game.players[i]||''}">`).join('');const valid=optionsFor(count);if(!valid.includes(imposterCount))imposterCount=valid[0];els.imposterOptions.innerHTML=valid.map(n=>`<button type="button" class="imposter-option ${n===imposterCount?'selected':''}" data-number="${n}" role="radio" aria-checked="${n===imposterCount}">${n} IMPOSTER${n>1?'S':''}</button>`).join('');els.imposterOptions.querySelectorAll('button').forEach(b=>b.onclick=()=>{imposterCount=+b.dataset.number;renderSetup()});}
function saveNames(){game.players=[...document.querySelectorAll('.name-input')].map(i=>i.value)}
document.getElementById('minusBtn').onclick=()=>{if(count>2){saveNames();count--;renderSetup()}};document.getElementById('plusBtn').onclick=()=>{if(count<10){saveNames();count++;renderSetup()}};
document.getElementById('setupForm').onsubmit=e=>{e.preventDefault();saveNames();const trimmed=game.players.map(n=>n.trim());if(trimmed.some(n=>!n)){els.formError.textContent='Please enter a name for everyone.';return}if(new Set(trimmed.map(n=>n.toLowerCase())).size!==trimmed.length){els.formError.textContent='Give duplicate names a nickname so the pass is clear.';return}els.formError.textContent='';game.players=trimmed;game.round=0;game.recentSecrets=[];game.recentImposters=[];startRound()};
function chooseImposters(){
  const recentSet=new Set(game.recentImposters);
  const preferred=shuffle(game.players.map((_,i)=>i).filter(i=>!recentSet.has(i)));
  const chosen=preferred.slice(0,Math.min(imposterCount,preferred.length));
  if(chosen.length>=imposterCount)return chosen;
  const remaining=shuffle(game.players.map((_,i)=>i).filter(i=>!chosen.includes(i)));
  return [...chosen,...remaining.slice(0,imposterCount-chosen.length)];
}
function startRound(){game.round++;const candidates=secretBank.filter(([s])=>!game.recentSecrets.includes(s));const [secret]=candidates[Math.floor(Math.random()*candidates.length)];game.recentSecrets=[...game.recentSecrets,secret].slice(-12);const imposters=chooseImposters();game.recentImposters=[...game.recentImposters,...imposters].slice(-Math.max(game.players.length,imposterCount));game.order=shuffle(game.players.map((_,i)=>i));game.secret=secret;game.hint=indirectHints[secret];game.imposters=imposters;game.position=0;els.roundNumber.textContent=game.round;show('handoffScreen');showHandoff();if(game.musicOn)startMusic()}
function showHandoff(){const index=game.order[game.position];els.currentPlayerName.textContent=game.players[index];els.progressFill.style.width=`${(game.position/game.players.length)*100}%`;els.progressText.textContent=`PLAYER ${game.position+1} OF ${game.players.length}`}
function show(id){['setupScreen','handoffScreen','roleScreen','endScreen'].forEach(k=>els[k].classList.toggle('hidden',k!==id))}
document.getElementById('readyBtn').onclick=()=>{const index=game.order[game.position],isImposter=game.imposters.includes(index);els.roleCard.classList.toggle('imposter',isImposter);els.roleIcon.textContent=isImposter?'🚨':'🟢';els.roleTitle.textContent=isImposter?'YOU ARE THE IMPOSTER':'YOU ARE NOT THE IMPOSTER';els.roleLabel.textContent=isImposter?'YOUR HINT':'YOUR SECRET';els.roleValue.textContent=isImposter?game.hint:game.secret;els.roleInstruction.textContent=isImposter?'Blend in. Give your own clue when the game starts.':'Create your own clue when the game starts.';els.nextBtn.textContent=game.position===game.players.length-1?'I HAVE SEEN IT ✅':'PASS TO NEXT PLAYER ➡️';show('roleScreen')};
els.nextBtn.onclick=()=>{game.position++;if(game.position>=game.players.length){show('endScreen')}else{show('handoffScreen');showHandoff()}};
document.getElementById('newRoundBtn').onclick=startRound;document.getElementById('newGameBtn').onclick=()=>{game={players:[],round:0,recentSecrets:[],recentImposters:[],musicOn:game.musicOn};count=4;imposterCount=1;renderSetup();show('setupScreen')};
function startMusic(){const music=document.getElementById('bgMusic');if(!music)return;music.volume=.60;music.play().catch(()=>{});}
function stopMusic(){const music=document.getElementById('bgMusic');if(!music)return;music.pause();music.currentTime=0;}
els.musicBtn.onclick=()=>{game.musicOn=!game.musicOn;els.musicBtn.setAttribute('aria-pressed',game.musicOn);els.musicBtn.querySelector('span').textContent=game.musicOn?'MUSIC ON':'MUSIC OFF';game.musicOn?startMusic():stopMusic()};renderSetup();
