const secretBank = [
 ['Bhat','Rice'],
 ['Tarkari','Curry'],
 ['Dal','Lentil'],
 ['Roti','Round'],
 ['Masu','Meat'],
 ['Sukuti','Dry'],
 ['Achar','Pickle'],
 ['Timur','Numb'],
 ['Jimbu','Aroma'],
 ['Ghee','Butter'],
 ['Paneer','Cheese'],
 ['Buff','Chewy'],
 ['Khasi','Goat'],
 ['Kukhura','Feather'],
 ['Egg','Shell'],
 ['Noodles','Slurp'],
 ['Fried Rice','Wok'],
 ['Pizza','Cheese'],
 ['Burger','Bun'],
 ['Kebab','Skewer'],
 ['HSP','Chips'],
 ['Donut','Hole'],
 ['Cake','Birthday'],
 ['Tim Tam','Dunk'],
 ['Milo','Chocolate'],
 ['Ice Cream','Cold'],
 ['Chocolate','Sweet'],
 ['Popcorn','Cinema'],
 ['Biryani','Aroma'],
 ['Naan','Tandoor'],
 ['Tongba','Bamboo'],
 ['Rakshi','Strong'],
 ['Dahi','Sour'],
 ['Kheer','Rice'],
 ['Aloo Chop','Potato'],
 ['Pakoda','Crispy'],
 ['Taas','Spicy'],
 ['Thakali','Set'],
 ['Kwati','Beans'],
 ['Fulpati','Flowers'],
 ['Jamara','Yellow'],
 ['Tika','Forehead'],
 ['Laxmi Puja','Wealth'],
 ['Kukur Tihar','Dogs'],
 ['Rangoli','Colour'],
 ['Diya','Flame'],
 ['Mala','Flowers'],
 ['Puja','Prayer'],
 ['Mandir','Bell'],
 ['Ghanti','Sound'],
 ['Prasad','Offering'],
 ['Kalash','Water'],
 ['Sindoor','Red'],
 ['Pote','Green'],
 ['Chura','Bangles'],
 ['Mehendi','Hands'],
 ['Saree','Draped'],
 ['Dhaka Topi','Pattern'],
 ['Madal','Rhythm'],
 ['Khukuri','Blade'],
 ['Gai Jatra','Cow'],
 ['Shivaratri','Temple'],
 ['Buddha Jayanti','Peace'],
 ['Losar','Mountains'],
 ['Aarti','Flame'],
 ['Namaste','Greeting'],
 ['Jhapa','Terai'],
 ['Biratnagar','Industry'],
 ['Janakpur','Temple'],
 ['Dhulikhel','View'],
 ['Bandipur','Old'],
 ['Gorkha','Palace'],
 ['Manang','Altitude'],
 ['Kali Gandaki','River'],
 ['Annapurna','Trek'],
 ['Langtang','Trek'],
 ['Makalu','Peak'],
 ['Kanchenjunga','Border'],
 ['Sagarmatha','Peak'],
 ['Terai','Flat'],
 ['Pahad','Hills'],
 ['Danda','Slope'],
 ['Khola','Water'],
 ['Jharana','Falls'],
 ['Pokhari','Pond'],
 ['Jungle','Wild'],
 ['Gaun','Village'],
 ['Bazaar','Shopping'],
 ['Chowk','Junction'],
 ['Galli','Narrow'],
 ['Tole','Neighbourhood'],
 ['Aagan','Courtyard'],
 ['Khet','Paddy'],
 ['Bari','Vegetables'],
 ['Goth','Cattle'],
 ['Pul','Crossing'],
 ['Janakpur Railway','Train'],
 ['Dharahara','Tower'],
 ['Rani Pokhari','Temple'],
 ['Asan','Market'],
 ['Indra Chowk','Market'],
 ['Patan','Crafts'],
 ['Patan Durbar Square','Courtyard'],
 ['Kirtipur','Hill'],
 ['Passport','Travel'],
 ['Visa','Approval'],
 ['IELTS','English'],
 ['PTE','Computer'],
 ['Consultancy','Agents'],
 ['Migration','Australia'],
 ['Medicare','Healthcare'],
 ['TFN','Tax'],
 ['ABN','Business'],
 ['Super','Retirement'],
 ['Payslip','Salary'],
 ['Tax','Government'],
 ['Refund','Money'],
 ['University','Degree'],
 ['College','Study'],
 ['Exam','Stress'],
 ['Graduation','Gown'],
 ['Certificate','Qualification'],
 ['Bachelor','Degree'],
 ['Masters','Postgraduate'],
 ['Resume','Jobs'],
 ['Interview','Questions'],
 ['Job','Salary'],
 ['Boss','Manager'],
 ['Worker','Salary'],
 ['Warehouse','Pallet'],
 ['Factory','Machines'],
 ['Office','Desk'],
 ['Tradie','Tools'],
 ['Tiler','Grout'],
 ['Carpenter','Timber'],
 ['Roster','Shifts'],
 ['Timesheet','Hours'],
 ['Overtime','Money'],
 ['Rent','Weekly'],
 ['Bond','Deposit'],
 ['Lease','Contract'],
 ['Bills','Monthly'],
 ['Coles','Groceries'],
 ['Woolworths','Rewards'],
 ['Aldi','Cheap'],
 ['Kmart','Cheap'],
 ['Big W','Shopping'],
 ['Bunnings','Sausage'],
 ['Target','Clothes'],
 ['JB Hi-Fi','Electronics'],
 ['Costco','Bulk'],
 ['Chemist Warehouse','Medicine'],
 ['Officeworks','Stationery'],
 ['IGA','Local'],
 ['Spudshed','Vegetables'],
 ['McDonald\'s','Drive'],
 ['KFC','Oil'],
 ['Hungry Jack\'s','Whopper'],
 ['Subway','Yummy'],
 ['Domino\'s','Delivery'],
 ['Nando\'s','Chicken'],
 ['GYG','Mexican'],
 ['Trolley','Groceries'],
 ['Basket','Shopping'],
 ['Checkout','Payment'],
 ['Receipt','Proof'],
 ['Discount','Sale'],
 ['Australia Post','Parcel'],
 ['Bus','Stop'],
 ['Train','Platform'],
 ['Tram','Tracks'],
 ['Ferry','Water'],
 ['Aeroplane','Flight'],
 ['Airport','Security'],
 ['Uber','Rating'],
 ['Taxi','Meter'],
 ['Car','Drive'],
 ['Motorcycle','Helmet'],
 ['Bicycle','Pedal'],
 ['Scooter','Electric'],
 ['Highway','Speed'],
 ['Freeway','Traffic'],
 ['Roundabout','Circle'],
 ['Traffic Light','Red'],
 ['Train Station','Ticket'],
 ['Boarding Pass','Gate'],
 ['Suitcase','Travel'],
 ['Luggage','Airport'],
 ['Seatbelt','Safety'],
 ['Steering Wheel','Driving'],
 ['Tyre','Puncture'],
 ['Petrol','Expensive'],
 ['Car Wash','Foam'],
 ['Speed Camera','Fine'],
 ['Hotel','Holiday'],
 ['Backpack','Travel'],
 ['Fridge','Cold'],
 ['Freezer','Ice'],
 ['Microwave','Heat'],
 ['Oven','Baking'],
 ['Dishwasher','Plates'],
 ['Washing Machine','Clothes'],
 ['Dryer','Laundry'],
 ['Vacuum','Dust'],
 ['Mop','Floor'],
 ['Bucket','Water'],
 ['Sofa','Sitting'],
 ['Mattress','Sleep'],
 ['Pillow','Head'],
 ['Blanket','Warm'],
 ['Curtain','Window'],
 ['Television','Remote'],
 ['Remote','Buttons'],
 ['Fan','Wind'],
 ['Air Conditioner','Cooling'],
 ['Rice Cooker','Bhat'],
 ['Pressure Cooker','Whistle'],
 ['Air Fryer','Crispy'],
 ['Kettle','Boiling'],
 ['Toaster','Bread'],
 ['Blender','Smoothie'],
 ['Iron','Clothes'],
 ['Hanger','Wardrobe'],
 ['Clothesline','Laundry'],
 ['Toothbrush','Teeth'],
 ['Toothpaste','Mint'],
 ['Soap','Bubbles'],
 ['Shampoo','Hair'],
 ['Towel','Dry'],
 ['Mirror','Reflection'],
 ['Door','Lock'],
 ['Window','Glass'],
 ['Keys','Lock'],
 ['Light Bulb','Electricity'],
 ['Kangaroo','Jump'],
 ['Koala','Eucalyptus'],
 ['Emu','Tall'],
 ['Dingo','Wild'],
 ['Magpie','Attack'],
 ['Cockatoo','Screech'],
 ['Seagull','Chips'],
 ['Crocodile','River'],
 ['Shark','Ocean'],
 ['Dolphin','Jump'],
 ['Whale','Giant'],
 ['Penguin','Ice'],
 ['Turtle','Shell'],
 ['Snake','Venom'],
 ['Spider','Web'],
 ['Dog','Bark'],
 ['Cat','Purr'],
 ['Cow','Milk'],
 ['Buffalo','Field'],
 ['Goat','Mountain'],
 ['Horse','Gallop'],
 ['Elephant','Trunk'],
 ['Tiger','Stripes'],
 ['Lion','Roar'],
 ['Monkey','Banana'],
 ['Perth','WA'],
 ['Sydney','Opera'],
 ['Melbourne','Coffee'],
 ['Brisbane','River'],
 ['Adelaide','Wine'],
 ['Canberra','Capital'],
 ['Gold Coast','Surf'],
 ['Fremantle','Prison'],
 ['Kings Park','Flowers'],
 ['Rottnest','Island'],
 ['Swan River','Boats'],
 ['Bondi Beach','Surf'],
 ['Opera House','Shell'],
 ['Harbour Bridge','Sydney'],
 ['Great Barrier Reef','Coral'],
 ['Uluru','Red'],
 ['Blue Mountains','Three'],
 ['Great Ocean Road','Cliffs'],
 ['Beach','Sand'],
 ['Outback','Desert'],
 ['PlayStation','Gaming'],
 ['Xbox','Gaming'],
 ['Nintendo','Mario'],
 ['Controller','Buttons'],
 ['Keyboard','Typing'],
 ['Mouse','Clicking'],
 ['Headset','Audio'],
 ['Monitor','Screen'],
 ['Computer','Work'],
 ['Laptop','Portable'],
 ['Smartphone','Pocket'],
 ['iPhone','Apple'],
 ['Samsung','Galaxy'],
 ['Charger','Battery'],
 ['Powerbank','Emergency'],
 ['Earbuds','Wireless'],
 ['Camera','Photos'],
 ['Tripod','Stable'],
 ['Microphone','Voice'],
 ['Router','Internet'],
 ['Netflix','Streaming'],
 ['Spotify','Music'],
 ['Instagram','Photos'],
 ['Discord','Chat'],
 ['WhatsApp','Messages'],
 ['Google','Search'],
 ['Gmail','Email'],
 ['Bluetooth','Wireless'],
 ['USB','Cable'],
 ['Password','Security'],
 ['Cricket','Bat'],
 ['Football','Goal'],
 ['Futsal','Indoor'],
 ['Volleyball','Net'],
 ['Badminton','Shuttle'],
 ['Basketball','Hoop'],
 ['Kabaddi','Breath'],
 ['Chess','Checkmate'],
 ['UNO','Cards'],
 ['Playing Cards','Shuffle'],
 ['Dice','Roll'],
 ['Cricket Bat','Willow'],
 ['Cricket Ball','Yorker'],
 ['Goalpost','Net'],
 ['Jersey','Team'],
 ['Trophy','Winner'],
 ['Medal','Podium'],
 ['Poker','Bluff'],
 ['Board Game','Table'],
 ['Karaoke','Singing'],
 ['Football Boots','Studs'],
 ['Cricket Helmet','Safety'],
 ['Cricket Gloves','Wicket'],
 ['Birthday','Cake'],
 ['Party','Dance'],
 ['BBQ','Meat'],
 ['Camping','Tent'],
 ['Sunscreen','Sun'],
 ['Sunglasses','Summer'],
 ['Umbrella','Rain'],
 ['Picnic','Food'],
 ['Cinema','Movie'],
 ['Speaker','Sound'],
 ['Toolbox','Tradie'],
 ['Hammer','Nail'],
 ['Drill','Hole'],
 ['Guitar','Strings'],
 ['Fireworks','Sky'],
 ['Alarm Clock','Morning'],
 ['Laphing','Spicy'],
 ['Chhurpi','Hard']
];

// Every imposter clue is one indirect word — never a definition or a second clue.
const indirectHints = Object.fromEntries(secretBank);

const els = Object.fromEntries(['setupScreen','handoffScreen','roleScreen','endScreen','countOutput','namesArea','imposterOptions','formError','currentPlayerName','roundNumber','progressFill','progressText','roleCard','roleIcon','roleTitle','roleLabel','roleValue','roleInstruction','nextBtn','musicBtn'].map(id=>[id,document.getElementById(id)]));
let count=4, imposterCount=1, game={players:[],round:0,recentSecrets:[],recentImposters:[],audio:null,musicOn:false};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function optionsFor(n){return n<=5?[1]:n<=7?[1,2]:[1,2,3]}
function renderSetup(){els.countOutput.value=count;els.namesArea.innerHTML=Array.from({length:count},(_,i)=>`<input class="name-input" aria-label="Player ${i+1} name" placeholder="Player ${i+1} name" value="${game.players[i]||''}">`).join('');const valid=optionsFor(count);if(!valid.includes(imposterCount))imposterCount=valid[0];els.imposterOptions.innerHTML=valid.map(n=>`<button type="button" class="imposter-option ${n===imposterCount?'selected':''}" data-number="${n}" role="radio" aria-checked="${n===imposterCount}">${n} IMPOSTER${n>1?'S':''}</button>`).join('');els.imposterOptions.querySelectorAll('button').forEach(b=>b.onclick=()=>{imposterCount=+b.dataset.number;renderSetup()});}
function saveNames(){game.players=[...document.querySelectorAll('.name-input')].map(i=>i.value)}
document.getElementById('minusBtn').onclick=()=>{if(count>2){saveNames();count--;renderSetup()}};
document.getElementById('plusBtn').onclick=()=>{if(count<10){saveNames();count++;renderSetup()}};
document.getElementById('setupForm').onsubmit=e=>{e.preventDefault();saveNames();const trimmed=game.players.map(n=>n.trim());if(trimmed.some(n=>!n)){els.formError.textContent='Please enter a name for everyone.';return}if(new Set(trimmed.map(n=>n.toLowerCase())).size!==trimmed.length){els.formError.textContent='Give duplicate names a nickname so the pass is clear.';return}els.formError.textContent='';game.players=trimmed;game.round=0;game.recentSecrets=[];game.recentImposters=[];startRound()};
function chooseImposters(){let pool=game.players.map((_,i)=>i);const fresh=pool.filter(i=>!game.recentImposters.includes(i));if(fresh.length>=imposterCount)pool=fresh;return shuffle(pool).slice(0,imposterCount)}
function startRound(){game.round++;const candidates=secretBank.filter(([s])=>!game.recentSecrets.includes(s));const [secret]=candidates[Math.floor(Math.random()*candidates.length)];game.recentSecrets=[...game.recentSecrets,secret].slice(-12);const imposters=chooseImposters();game.recentImposters=imposters;game.order=shuffle(game.players.map((_,i)=>i));game.secret=secret;game.hint=indirectHints[secret];game.imposters=imposters;game.position=0;els.roundNumber.textContent=game.round;show('handoffScreen');showHandoff();if(game.musicOn)startMusic()}
function showHandoff(){const index=game.order[game.position];els.currentPlayerName.textContent=game.players[index];els.progressFill.style.width=`${(game.position/game.players.length)*100}%`;els.progressText.textContent=`PLAYER ${game.position+1} OF ${game.players.length}`}
function show(id){['setupScreen','handoffScreen','roleScreen','endScreen'].forEach(k=>els[k].classList.toggle('hidden',k!==id))}
document.getElementById('readyBtn').onclick=()=>{const index=game.order[game.position],isImposter=game.imposters.includes(index);els.roleCard.classList.toggle('imposter',isImposter);els.roleIcon.textContent=isImposter?'🚨':'🟢';els.roleTitle.textContent=isImposter?'YOU ARE THE IMPOSTER':'YOU ARE NOT THE IMPOSTER';els.roleLabel.textContent=isImposter?'YOUR HINT':'YOUR SECRET';els.roleValue.textContent=isImposter?game.hint:game.secret;els.roleInstruction.textContent=isImposter?'Blend in. Give your own clue when the game starts.':'Create your own clue when the game starts.';els.nextBtn.textContent=game.position===game.players.length-1?'I HAVE SEEN IT ✅':'PASS TO NEXT PLAYER ➡️';show('roleScreen')};
els.nextBtn.onclick=()=>{game.position++;if(game.position>=game.players.length){show('endScreen')}else{show('handoffScreen');showHandoff()}};
document.getElementById('newRoundBtn').onclick=startRound;
document.getElementById('newGameBtn').onclick=()=>{game={players:[],round:0,recentSecrets:[],recentImposters:[],audio:game.audio,musicOn:game.musicOn};count=4;imposterCount=1;renderSetup();show('setupScreen')};
function startMusic(){if(!game.audio){const C=window.AudioContext||window.webkitAudioContext;game.audio=new C()}const c=game.audio;if(c.state==='suspended')c.resume();if(game.musicTimer)return;const notes=[261.63,329.63,392,329.63,293.66,369.99,440,369.99];let x=0;game.musicTimer=setInterval(()=>{const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=notes[x++%notes.length];g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.028,c.currentTime+.025);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.32);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.34)},390)}
function stopMusic(){clearInterval(game.musicTimer);game.musicTimer=null}
els.musicBtn.onclick=()=>{game.musicOn=!game.musicOn;els.musicBtn.setAttribute('aria-pressed',game.musicOn);els.musicBtn.querySelector('span').textContent=game.musicOn?'MUSIC ON':'MUSIC OFF';game.musicOn?startMusic():stopMusic()};
renderSetup();
